# Permalinks
#
permalink:           pretty
markdown:            kramdown

# Setup
title:               Ames Housing Data
tagline:             'analysis and predictive modeling'
description:         'Analysis and predictive modeling of sale prices in Ames Housing Dataset.'
url:                 127.0.0.1:4000
baseurl:             /temp

# About/contact
author:
  name:              Ryan Wenzel
  url:               https://rmwenzel.com
  email:             rmwenzel@uw.edu

kramdown:
  parse_block_html: true

