# Permalinks
#
permalink:           pretty
markdown:            kramdown

# Setup
title:               Ames Housing Data
tagline:             'Processing, analysis and predictive modeling'
description:         'Processing, analysis and predictive modeling of sale prices in Ames Housing Dataset.'
url:                 https://rmwenzel.com
baseurl:             /ames_house_prices

# About/contact
author:
  name:              Ryan Wenzel
  url:               https://rmwenzel.com
  email:             rmwenzel@uw.edu

kramdown:
  parse_block_html: true

plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-katex

